import { Category } from '@/types';

export const mockCategories: Category[] = [
  {
    id: 'cat-single-origin',
    slug: 'single-origin',
    name: 'Моносорта & Микролоты',
    shortDescription: 'Отборное зерно свежей обжарки со всего мира с ярким терруаром.',
    longDescription: 'Коллекция моносортов 100% спешелти арабики из Эфиопии, Колумбии, Кении, Гватемалы и Бразилии. Чистый вкусовой профиль, натуральная и мытая обработка, раскрывающиеся нотами цветов, ягод и цитрусов.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    accentColor: '#D9A76A',
    order: 1,
  },
  {
    id: 'cat-espresso-blends',
    slug: 'espresso-blends',
    name: 'Эспрессо-бленды',
    shortDescription: 'Сбалансированные купажи для плотного эспрессо и молочных напитков.',
    longDescription: 'Фирменные авторские смеси ТАВ средней и темной обжарки. Густая шелковистая пенка крема, ноты темного шоколада, жареных орехов и карамели без лишней кислотности.',
    imageUrl: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?q=80&w=800&auto=format&fit=crop',
    accentColor: '#C2905A',
    order: 2,
  },
  {
    id: 'cat-drip-coffee',
    slug: 'drip-coffee',
    name: 'Дрип-пакеты',
    shortDescription: 'Спешелти кофе в чашке за 2 минуты: дома, в офисе и путешествиях.',
    longDescription: 'Свежесмолотый спешелти кофе, упакованный в бескислородной среде с азотом. Просто установите дрип-пакет на любимую чашку и пролейте горячей водой.',
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=800&auto=format&fit=crop',
    accentColor: '#B88B58',
    order: 3,
  },
  {
    id: 'cat-sets',
    slug: 'sets',
    name: 'Дегустационные сеты',
    shortDescription: 'Подарочные боксы и наборы сортов для кофейных открытий.',
    longDescription: 'Наборы микролотов и ассорти дрип-пакетов в стильной премиальной упаковке ТАВ. Идеальный подарок для себя и ценителей изысканного кофе.',
    imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
    accentColor: '#E5CBA8',
    order: 4,
  },
  {
    id: 'cat-accessories',
    slug: 'accessories',
    name: 'Аксессуары и заваривание',
    shortDescription: 'Воронки V60, ручные кофемолки, фильтры и серверы.',
    longDescription: 'Профессиональное оборудование для альтернативного заваривания кофе дома: керамические воронки, бумажные фильтры, серверы из термостекла и точные весы.',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
    accentColor: '#8E8276',
    order: 5,
  },
];
