import { PageData } from '@/lib/db/pages';

export const mockPages: PageData[] = [
  {
    id: 'page-home',
    slug: 'home',
    title: 'Главная страница',
    seoTitle: 'ТАВ — Спешелти кофе свежей обжарки в Майкопе | Каталог и дрип-пакеты',
    seoDescription: 'Спешелти кофе свежей еженедельной обжарки от ТАВ: моносорта из Эфиопии, Колумбии, Кении, фирменные эспрессо-купажи и порционные дрип-пакеты в Майкопе.',
    seoKeywords: 'кофе, спешелти кофе, майкоп, обжарка кофе, дрип-пакеты, кофе в зернах',
    ogImage: '/images/hero-bg.jpg',
    isPublished: true,
    blocks: [
      {
        id: 'blk-home-hero',
        pageId: 'page-home',
        blockType: 'hero',
        name: 'Первый экран (Hero)',
        order: 1,
        isActive: true,
        content: {
          badge: 'SPECIALTY COFFEE ROASTERS • МАЙКОП',
          headline: 'Спешелти кофе свежей обжарки',
          headlineAccent: 'в Майкопе',
          cursiveSubtitle: 'От терруара к совершенной чашке',
          description: 'Отборные микролоты со всего мира. Еженедельная обжарка, раскрывающая истинный профиль зерна, и бесплатный помол.',
          primaryButton: { label: 'Каталог кофе', href: '/catalog' },
          secondaryButton: { label: 'О бренде ТАВ', href: '/about' },
          metrics: [
            { value: '100%', label: 'Спешелти Арабика' },
            { value: '84–89+', label: 'Баллы SCA' },
            { value: '0 ₽', label: 'Помол в подарок' },
          ],
        },
      },
      {
        id: 'blk-home-directions',
        pageId: 'page-home',
        blockType: 'directions',
        name: 'Направления кофе ТАВ',
        order: 2,
        isActive: true,
        content: {
          badge: 'КОЛЛЕКЦИЯ ТАВ',
          title: 'Кофе для любого настроения и способа заваривания',
          subtitle: 'От сочных ягодных моносортов под воронку до плотных орехово-шоколадных эспрессо-смесей.',
        },
      },
      {
        id: 'blk-home-popular',
        pageId: 'page-home',
        blockType: 'featured_products_popular',
        name: 'Популярный спешелти кофе',
        order: 3,
        isActive: true,
        content: {
          badge: 'Выбор недели',
          title: 'Популярный спешелти кофе',
          subtitle: 'Сбалансированные эспрессо-купажи, яркие моносорта и порционный дрип-кофе, которые выбирают наши гости.',
          actionLabel: 'Смотреть весь каталог',
          actionHref: '/catalog',
          limit: 6,
        },
      },
      {
        id: 'blk-home-new',
        pageId: 'page-home',
        blockType: 'featured_products_new',
        name: 'Новинки коллекции ТАВ',
        order: 4,
        isActive: true,
        content: {
          badge: 'Свежие микролоты',
          title: 'Новинки коллекции ТАВ',
          subtitle: 'Свежие поступления зерна нового урожая, лимитированная анаэробная ферментация и аксессуары для заваривания.',
          actionLabel: 'Все новинки кофе',
          actionHref: '/catalog?isNew=true',
          limit: 6,
        },
      },
      {
        id: 'blk-home-collections',
        pageId: 'page-home',
        blockType: 'collections_grid',
        name: 'Тематические подборки',
        order: 5,
        isActive: true,
        content: {
          badge: 'ПОДБОРКИ ТАВ',
          title: 'Кофе под ваш вкус и метод',
          subtitle: 'Специально сгруппированные наборы для фильтра, эспрессо и путешествий.',
        },
      },
      {
        id: 'blk-home-about',
        pageId: 'page-home',
        blockType: 'about_snippet',
        name: 'О философии ТАВ',
        order: 6,
        isActive: true,
        content: {
          badge: 'ФИЛОСОФИЯ ТАВ',
          title: '«Мы обжариваем зерно так, чтобы раскрыть его природный характер»',
          description: 'Кофе — это сложная вкусовая палитра. Мы подбираем индивидуальный профиль обжарки для каждого мешка зеленого кофе, сохраняя баланс природной сладости, плотности и тонкой кислотности.',
          actionLabel: 'Узнать больше о нас',
          actionHref: '/about',
        },
      },
      {
        id: 'blk-home-stores',
        pageId: 'page-home',
        blockType: 'stores_section',
        name: 'Где нас найти (Локация и Карта)',
        order: 7,
        isActive: true,
        content: {
          badge: 'ПРОСТРАНСТВО ТАВ',
          title: 'Ждем вас на дегустацию в Майкопе',
          subtitle: 'Приходите вдохнуть ароматы свежей обжарки, выбрать зерно или забрать онлайн-заказ.',
        },
      },
    ],
  },
  {
    id: 'page-about',
    slug: 'about',
    title: 'О бренде ТАВ',
    seoTitle: 'О бренде ТАВ — Культура спешелти кофе в Майкопе',
    seoDescription: 'История и философия ТАВ: почему мы сосредоточились на спешелти кофе свежей обжарки, выборе редких микролотов и культуре заваривания в Майкопе.',
    seoKeywords: 'о бренде тав, обжарщики майкоп, история спешелти',
    ogImage: '/images/hero-bg.jpg',
    isPublished: true,
    blocks: [
      {
        id: 'blk-about-hero',
        pageId: 'page-about',
        blockType: 'hero',
        name: 'Hero «О бренде»',
        order: 1,
        isActive: true,
        content: {
          badge: 'ТАВ • SPECIALTY COFFEE ROASTERS',
          headline: '«Мы обжариваем зерно так, чтобы раскрыть его истинную природу»',
          description: 'ТАВ — это пространство, где кофе рассматривается как искусство. От тщательного отбора зеленого зерна на фермах до ювелирной калибровки профиля обжарки на ростере.',
          metrics: [
            { value: '100%', label: 'Спешелти Арабика' },
            { value: '84–89+', label: 'Баллы SCA' },
            { value: '0 ₽', label: 'Помол в подарок' },
          ],
        },
      },
      {
        id: 'blk-about-philosophy',
        pageId: 'page-about',
        blockType: 'philosophy',
        name: 'Философия обжарки',
        order: 2,
        isActive: true,
        content: {
          badge: 'ФИЛОСОФИЯ ОБЖАРКИ ТАВ',
          title: 'Чистый вкус зерна без компромиссов',
          description1: 'Кофе — это живая ягода, отражающая климат, почву и высоту произрастания. Мы не прячем дефекты сырья за сверхтёмной обжаркой, а подбираем профили, подчеркивающие природную сладость, сочную кислотность и букет дескрипторов.',
          description2: 'Каждый лот в коллекции ТАВ проходит многократные дегустации (каппинги) и получает подробный вкусовой паспорт с оценкой SCA.',
        },
      },
      {
        id: 'blk-about-standards',
        pageId: 'page-about',
        blockType: 'standards',
        name: '3 правила бренда ТАВ',
        order: 3,
        isActive: true,
        content: {
          badge: 'СТАНДАРТЫ КАЧЕСТВА ТАВ',
          title: '3 правила бренда ТАВ',
          subtitle: 'От строгого отбора зеленого сырья до упаковки и помола зерна в присутствии гостя.',
          rules: [
            {
              number: '01',
              badge: 'SCA 84–89+',
              title: 'Только 100% Спешелти зерно',
              description: 'Никакой коммерческой робусты и дефектного зерна. Мы работаем с лотами с прозрачным происхождением и подтвержденной историей фермы.',
            },
            {
              number: '02',
              badge: 'До 14 дней',
              title: 'Свежесть и контроль обжарки',
              description: 'Обжариваем небольшими партиями каждую неделю. Пакеты с односторонним дегазационным клапаном сохраняют сочные эфирные масла.',
            },
            {
              number: '03',
              badge: 'Бесплатно 0 ₽',
              title: 'Профессиональный помол',
              description: 'Мы бесплатно смолем зерно под ваш метод (турка, эспрессо, гейзер, воронка V60, френч-пресс) прямо при вас.',
            },
          ],
        },
      },
      {
        id: 'blk-about-callout',
        pageId: 'page-about',
        blockType: 'callout_banner',
        name: 'Баннер приглашения в кофейню',
        order: 4,
        isActive: true,
        content: {
          badge: 'ПРОСТРАНСТВО ТАВ В МАЙКОПЕ',
          title: 'Ждем вас на дегустацию свежего зерна',
          description: 'Приходите вдохнуть ароматы свежей обжарки, подобрать дрип-кофе и аксессуары или забрать онлайн-заказ.',
          buttonPrimary: { label: 'Контакты и адрес', href: '/contacts' },
          buttonSecondary: { label: 'Каталог кофе', href: '/catalog' },
        },
      },
    ],
  },
  {
    id: 'page-coffee',
    slug: 'coffee',
    title: 'Зерновой кофе & Дрипы',
    seoTitle: 'Зерновой кофе & Дрип-пакеты — Спешелти свежей обжарки | ТАВ',
    seoDescription: 'Отборный спешелти кофе со всего мира: Эфиопия, Колумбия, Кения, Коста-Рика, Бразилия, Гватемала. Светлая, средняя и тёмная обжарка, дрип-пакеты, бесплатный помол в ТАВ.',
    seoKeywords: 'зерновой кофе, дрип-пакеты, эфиопия, колумбия, кения, свежая обжарка',
    ogImage: '/images/hero-bg.jpg',
    isPublished: true,
    blocks: [
      {
        id: 'blk-coffee-hero',
        pageId: 'page-coffee',
        blockType: 'hero',
        name: 'Hero страницы Кофе',
        order: 1,
        isActive: true,
        content: {
          badge: '100% Specialty Arabica • Свежая обжарка ТАВ',
          headline: 'Коллекция спешелти кофе ТАВ',
          cursiveSubtitle: 'От цветочной Эфиопии до бархатной Бразилии',
          description: 'Микролоты отборного зерна со всего мира для ценителей чистого вкуса. Индивидуальные профили обжарки, раскрывающие уникальный терруар, и бесплатный помол в Майкопе.',
          metrics: [
            { value: 'до 14 дней', label: 'Свежая обжарка' },
            { value: 'Q 84–89+', label: 'SCA Грейдинг' },
            { value: '0 ₽', label: 'Помол в подарок' },
          ],
        },
      },
      {
        id: 'blk-coffee-roast',
        pageId: 'page-coffee',
        blockType: 'roast_guide',
        name: 'Гид по степеням обжарки',
        order: 2,
        isActive: true,
        content: {
          badge: 'ГИД ПО ОБЖАРКЕ ТАВ',
          title: 'Как выбрать идеальную обжарку',
          subtitle: 'Каждая степень обжарки создается для раскрытия определенных дескрипторов и методов заваривания.',
          profiles: [
            {
              levelKey: 'light',
              title: 'Светлая обжарка (Light)',
              badge: 'Для ценителей',
              subtitle: 'Цветы, бергамот и сочные спелые фрукты',
              description: 'Раскрывает истинный терруар и природную сочность кофейной ягоды.',
              flavorNotes: ['Бергамот', 'Жасмин', 'Белый персик', 'Лайм'],
              recommendedBrew: 'V60 воронка, Кемекс, Аэропресс, Фильтр-кофеварка',
              acidity: 5,
              body: 2,
              sweetness: 4,
              bitterness: 1,
              recommendedProductId: null,
            },
            {
              levelKey: 'medium',
              title: 'Средняя обжарка (Medium)',
              badge: 'Хит & Баланс',
              subtitle: 'Карамель, молочный шоколад и баланс',
              description: 'Самый гармоничный и универсальный профиль.',
              flavorNotes: ['Молочный шоколад', 'Карамель', 'Красное яблоко', 'Фундук'],
              recommendedBrew: 'Гейзерная кофеварка (Moka), Автоматическая кофемашина, Эспрессо',
              acidity: 3,
              body: 4,
              sweetness: 5,
              bitterness: 2,
              recommendedProductId: null,
            },
            {
              levelKey: 'dark',
              title: 'Тёмная обжарка (Dark Espresso)',
              badge: 'Классика',
              subtitle: 'Плотное тело, темный шоколад и какао',
              description: 'Густой, плотный и маслянистый эспрессо-профиль без лишней кислотности.',
              flavorNotes: ['Тёмный шоколад', 'Жареный фундук', 'Патока', 'Какао'],
              recommendedBrew: 'Классический эспрессо, Капучино, Латте, Турка (Джезва)',
              acidity: 1,
              body: 5,
              sweetness: 3,
              bitterness: 4,
              recommendedProductId: null,
            },
          ],
        },
      },
      {
        id: 'blk-coffee-terroir',
        pageId: 'page-coffee',
        blockType: 'terroir_atlas',
        name: 'Атлас терруаров',
        order: 3,
        isActive: true,
        content: {
          badge: 'География микролотов',
          title: 'Мировые терруары в коллекции ТАВ',
          subtitle: 'Выберите регион происхождения, чтобы исследовать высоту произрастания, метод обработки и уникальный вкусовой букет кофейного зерна.',
          items: [
            {
              id: 'ethiopia-yirgacheffe',
              countryId: 'country-ethiopia',
              region: 'Иргачиф (Yirgacheffe)',
              continent: 'Восточная Африка',
              altitude: '1900 – 2200 м',
              process: 'Мытая обработка (Washed)',
              sommelierNotes: 'Спешелти микролот высшей категории с высокогорных склонов Эфиопии. Яркий букет белых цветов и цитрусовых нот.',
              flavorNotes: ['Бергамот', 'Жасмин', 'Белый персик', 'Лайм'],
              imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=1200&auto=format&fit=crop',
              productId: null,
              order: 1,
              isActive: true,
            },
            {
              id: 'colombia-huila',
              countryId: 'country-colombia',
              region: 'Уила (Huila)',
              continent: 'Южная Америка',
              altitude: '1600 – 1900 м',
              process: 'Мытая обработка (Washed)',
              sommelierNotes: 'Гармоничный профиль из долины Уила: сочное красное яблоко, карамельная сладость и бархатное тело.',
              flavorNotes: ['Красное яблоко', 'Карамель', 'Тростниковый сахар'],
              imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1200&auto=format&fit=crop',
              productId: null,
              order: 2,
              isActive: true,
            },
            {
              id: 'kenya-nyeri',
              countryId: 'country-kenya',
              region: 'Ньери (Nyeri)',
              continent: 'Восточная Африка',
              altitude: '1750 – 2100 м',
              process: 'Двойная ферментация',
              sommelierNotes: 'Вулканические почвы горы Кения. Выразительная смородиновая кислотность, ноты грейпфрута и черного чая.',
              flavorNotes: ['Черная смородина', 'Грейпфрут', 'Красный чай'],
              imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1200&auto=format&fit=crop',
              productId: null,
              order: 3,
              isActive: true,
            },
          ],
        },
      },
      {
        id: 'blk-coffee-grinding',
        pageId: 'page-coffee',
        blockType: 'grinding_station',
        name: 'Бесплатный помол зерна',
        order: 4,
        isActive: true,
        content: {
          badge: 'Сервис в Майкопе • ул. К.А. Васильева, 2/1',
          headline: 'Бесплатный помол зерна',
          headlineHighlight: 'под ваш способ заваривания',
          description:
            'При покупке любого сорта мы бесплатно смолем зерно прямо в магазине под ваш любимый девайс — от пудры для джезвы до френч-пресса.',
          feature1: {
            title: 'Жернова Fiorenzato',
            desc: 'Без перегрева и пыли.',
          },
          feature2: {
            title: 'Помол за 60 секунд',
            desc: 'Свежий помол при вас.',
          },
          methods: [
            {
              number: '01',
              title: 'Турка (Джезва)',
              subtitle: 'Экстра-тонкий (пыль)',
              fraction: '≈ 0.1 мм',
              desc: 'Помол в нежнейшую пудру для плотного напитка с густой бархатистой пенкой.',
              time: '2–3 мин',
            },
            {
              number: '02',
              title: 'Эспрессо',
              subtitle: 'Тонкий калиброванный',
              fraction: '≈ 0.3 мм',
              desc: 'Фракция под давление 9 бар рожковой или автоматической кофемашины.',
              time: '25–30 сек',
            },
            {
              number: '03',
              title: 'Гейзер (Moka)',
              subtitle: 'Средне-тонкий помол',
              fraction: '≈ 0.5 мм',
              desc: 'Размер песчинок тростникового сахара. Не забивает фильтр гейзера.',
              time: '3–4 мин',
            },
            {
              number: '04',
              title: 'Фильтр & V60',
              subtitle: 'Средний помол',
              fraction: '≈ 0.8 мм',
              desc: 'Для воронки V60, фильтр-кофеварок и кемекса. Раскрывает ягоды и цветы.',
              time: '3–3.5 мин',
            },
            {
              number: '05',
              title: 'Френч-пресс',
              subtitle: 'Крупный помол',
              fraction: '≈ 1.2 мм',
              desc: 'Крупные гранулы для долгого настаивания и Cold Brew без кофейной пыли.',
              time: '4–5 мин',
            },
          ],
        },
      },
      {
        id: 'blk-coffee-collection',
        pageId: 'page-coffee',
        blockType: 'coffee_collection',
        name: 'Кофейная коллекция ТАВ',
        order: 5,
        isActive: true,
        content: {
          badge: 'Свежая обжарка в наличии',
          title: 'Кофейная коллекция ТАВ',
          subtitle: '',
        },
      },
      {
        id: 'blk-coffee-sensory',
        pageId: 'page-coffee',
        blockType: 'sensory_cycle',
        name: 'Стандарты свежести и сенсорный цикл',
        order: 6,
        isActive: true,
        content: {
          badge: 'Сенсорный контроль и стандарты',
          headline: 'Почему кофе ТАВ',
          headlineHighlight: 'раскрывается иначе',
          description:
            'Мы относимся к спешелти-кофе как к живому продукту: от строгого отбора мировых микролотов до контроля фаз созревания зерна после обжарки.',
          freshnessTitle: '«Золотое окно свежести»',
          freshnessBadge: 'Пик: 4–21 день',
          freshnessDesc:
            'Свой истинный букет, сочную сладость и плотную пенку crema арабика проявляет именно в «золотом окне» созревания.',
          phases: [
            {
              days: '1–3 день',
              title: 'Фаза активной дегазации',
              desc: 'Выход углекислого газа после ростера. Вкус зерна только начинает структурироваться.',
            },
            {
              days: '4–21 день',
              title: '✨ Пик вкусоароматики',
              desc: 'Максимум эфирных масел, сочная чистая кислотность и шелковистое тело в чашке.',
              highlight: true,
            },
            {
              days: '30+ дней',
              title: 'Медленное угасание',
              desc: 'Постепенное окисление тонких ягодных и цветочных дескрипторов.',
            },
          ],
          shelfBanner: {
            leftText: 'На полках в Майкопе:',
            rightText: 'Всегда свежая обжарка не старше 7–14 дней',
          },
          features: [
            {
              tag1: 'ТОП 10% УРОЖАЯ',
              tag2: '84+ SCA',
              title: '100% Specialty Arabica',
              desc: 'Ручной селекционный сбор ягод без дефектов. Прозрачное происхождение каждого микролота.',
            },
            {
              tag1: 'БАРЬЕРНАЯ ФОЛЬГА',
              tag2: 'WICOvalves',
              title: 'Клапан дегазации & Zip-Lock',
              desc: 'Трехслойный металлизированный барьер блокирует кислород, сохраняя 1000+ эфирных соединений.',
            },
            {
              tag1: 'В МАГАЗИНЕ',
              tag2: 'МАЙКОП',
              title: 'Помол в подарок на Васильева, 2/1',
              desc: 'Бесплатно смолем любую пачку на калиброванных жерновах под ваш девайс.',
            },
          ],
        },
      },
    ],
  },
  {
    id: 'page-contacts',
    slug: 'contacts',
    title: 'Контакты и локация',
    seoTitle: 'Контакты и пространство в Майкопе | ТАВ',
    seoDescription: 'Адрес, телефон и режим работы флагманского пространства ТАВ в Майкопе: ул. К.А. Васильева, 2/1. Маршрут в Яндекс Картах и 2ГИС, связь с бариста в Telegram и WhatsApp.',
    seoKeywords: 'контакты тав, майкоп васильева 2/1, телефон, карта',
    ogImage: '/images/store-maykop-interior.jpg',
    isPublished: true,
    blocks: [
      {
        id: 'blk-contacts-hero',
        pageId: 'page-contacts',
        blockType: 'hero',
        name: 'Hero Контактов',
        order: 1,
        isActive: true,
        content: {
          badge: 'МАЙКОП, УЛ. К.А. ВАСИЛЬЕВА, 2/1 • ПРОСТРАНСТВО ТАВ',
          headline: 'Контакты и',
          headlineHighlight: 'пространство ТАВ',
          cursiveSubtitle: 'Приходите за свежеобжаренным спешелти кофе и дегустацией',
          description:
            'Кофейное пространство в Майкопе: здесь можно вдохнуть ароматы свежих моносортов, подобрать дрип-пакеты в поездку, приобрести аксессуары Hario и бесплатно смолоть зерно под любой метод.',
          imageUrl: '/images/store-maykop-interior.jpg',
          highlights: [
            'Парковка перед входом',
            'Помол зерна 0 ₽',
            'Самовывоз 15 мин',
            'Pet-friendly',
          ],
        },
      },
      {
        id: 'blk-contacts-boutique',
        pageId: 'page-contacts',
        blockType: 'boutique_showcase',
        name: 'Витрины и интерьер шоурума',
        order: 2,
        isActive: true,
        content: {
          badge: 'Локация в Майкопе',
          title: 'Витрины и интерьер концепт-стора',
          zones: [
            {
              id: 'facade',
              label: '🏛️ Фасад & Вход',
              title: 'Главный вход и парковка',
              desc: 'Удобный подъезд с улицы Васильева, бесплатная автостоянка прямо перед входом.',
              image: '/images/store-maykop.jpg',
              order: 1,
              isActive: true,
            },
            {
              id: 'interior',
              label: '☕ Зона спешелти кофе',
              title: 'Кофейная витрина и дегустация',
              desc: 'Коллекция свежеобжаренных зерен ТАВ, образцы ароматов и зона бесплатного жернового помола.',
              image: '/images/store-maykop-interior.jpg',
              order: 2,
              isActive: true,
            },
            {
              id: 'drip',
              label: '📦 Дрип-бар & Аксессуары',
              title: 'Дрип-пакеты и аксессуары Hario & Timemore',
              desc: 'Порционный кофе в индивидуальных саше с азотом, керамические воронки V60, ручные кофемолки и фильтры.',
              image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1200&auto=format&fit=crop',
              order: 3,
              isActive: true,
            },
          ],
        },
      },
      {
        id: 'blk-contacts-map',
        pageId: 'page-contacts',
        blockType: 'map_section',
        name: 'Интерактивная карта и маршруты',
        order: 3,
        isActive: true,
        content: {
          badge: 'ИНТЕРАКТИВНАЯ КАРТА • МАЙКОП',
          title: 'Как добраться в концепт-стор',
          description:
            'Майкоп, ул. К.А. Васильева, 2/1 — бесплатная парковка перед входом, 330 м от остановки «Ул. 12-го Марта».',
          yandexMapUrl:
            'https://yandex.ru/map-widget/v1/?ll=40.046895%2C44.609943&z=17.2&pt=40.046895,44.609943,pm2rdm&mode=search&text=%D0%9C%D0%B0%D0%B9%D0%BA%D0%BE%D0%BF%2C%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B0%2C%202%2F1',
          yandexDirectUrl: 'https://yandex.ru/maps/-/CTDGNHK~',
          gisDirectUrl: 'https://2gis.ru/maykop/search/%D0%9C%D0%B0%D0%B9%D0%BA%D0%BE%D0%BF%20%D1%83%D0%BB.%20%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B0%2C%202%2F1',
          transportTips: [
            {
              icon: 'car',
              title: 'На автомобиле',
              desc: 'Удобный заезд с ул. Васильева. Бесплатная автостоянка прямо перед крыльцом.',
            },
            {
              icon: 'bus',
              title: 'Общественным транспортом',
              desc: 'Остановка «Улица 12-го Марта» (маршрутки и автобусы) — 4 минуты пешком (330 м).',
            },
            {
              icon: 'walk',
              title: 'Пешком',
              desc: 'Уютный район, яркая вывеска с подсветкой и вход с уровня тротуара.',
            },
          ],
        },
      },
      {
        id: 'blk-contacts-concierge',
        pageId: 'page-contacts',
        blockType: 'concierge_hub',
        name: 'Связь с залом и сервис в шоуруме',
        order: 4,
        isActive: true,
        content: {
          conciergeBadge: 'Персональный консьерж',
          conciergeTitle: 'Прямая связь с залом',
          conciergeDesc: 'Консультанты ответят в течение нескольких минут, снимут видео новинок и отложат товар.',
          telegramUrl: 'https://t.me/tav_coffee',
          whatsappUrl: 'https://wa.me/79881637141',
          mainPhone: '+7 (988) 163-71-41',
        },
      },
    ],
  },
  {
    id: 'page-privacy',
    slug: 'privacy',
    title: 'Политика конфиденциальности',
    seoTitle: 'Политика конфиденциальности | ТАВ Coffee',
    seoDescription: 'Политика обработки персональных данных и конфиденциальности ТАВ Coffee.',
    seoKeywords: 'конфиденциальность, согласие на обработку данных',
    ogImage: '/images/hero-bg.jpg',
    isPublished: true,
    blocks: [],
  },
];
