import { Product } from '@/types';

export const mockProducts: Product[] = [
  // ==========================================
  // МОНОСОРТА & МИКРОЛОТЫ (Single Origin)
  // ==========================================
  {
    id: 'prod-coffee-1',
    slug: 'ethiopia-yirgacheffe-washed',
    title: 'Ethiopia Yirgacheffe Washed Grade 1',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-et',
    countryName: 'Эфиопия',
    countryCode: 'ET',
    price: 890,
    inStock: true,
    stockCount: 14,
    description: 'Исключительно чистый и деликатный профиль высокогорной мытой арабики. Раскрывается свежими цитрусовыми нотами, жасмином и сладким белым персиком. Идеален для воронки V60, кемекса, аэропресса и капельной кофеварки.',
    shortDescription: 'Светлая обжарка с нотами бергамота, жасмина и белого персика.',
    images: [
      'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-02-15T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Эфиопское наследие)',
      roastLevel: 'light',
      processing: 'Мытая (Washed)',
      altitude: '1 950 – 2 200 м',
      qScore: 87.5,
      flavorNotes: ['Бергамот', 'Жасмин', 'Белый персик', 'Лайм'],
      recommendedBrew: ['V60 Воронка', 'Кемекс', 'Аэропресс', 'Фильтр'],
      acidity: 5,
      sweetness: 4,
      bitterness: 1,
      body: 2,
      weight: 250,
      recipe: {
        title: 'Идеальное приготовление в V60 / Фильтре',
        subtitle: 'Рецепт экстракции от шеф-бариста ТАВ',
        badge: '15 г : 250 мл',
        ratio: '15 г : 250 мл',
        ratioDesc: '1 : 16.6',
        temp: '92°C – 94°C',
        tempDesc: 'горячая вода',
        grind: 'Средний песок',
        grindDesc: 'под V60',
        time: '2:30 – 3:00',
        timeDesc: 'общее время',
        steps: [
          'Блуминг (предсмачивание): Влейте 45 мл воды и подождите 40 секунд для равномерной дегазации зерна.',
          'Первый пролив: Плавно долейте воду до 150 мл медленными концентрическими кругами от центра к краям.',
          'Второй пролив: Долейте до 250 мл строго по центру. Дайте воде полностью стечь в сервер.',
        ],
      },
    },
  },
  {
    id: 'prod-coffee-2',
    slug: 'colombia-huila-supremo',
    title: 'Colombia Huila Supremo Estate',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-co',
    countryName: 'Колумбия',
    countryCode: 'CO',
    price: 820,
    inStock: true,
    stockCount: 22,
    description: 'Классический южноамериканский баланс. Плотное кремовое тело, умеренная яблочная кислотность и согревающий орехово-карамельный шлейф. Превосходно раскрывается в эспрессо, гейзерной кофеварке и отлично сочетается с молоком.',
    shortDescription: 'Средняя обжарка с нотами красного яблока, молочного шоколада и карамели.',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-01-20T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Катурра, Колумбия)',
      roastLevel: 'medium',
      processing: 'Мытая (Washed)',
      altitude: '1 650 – 1 850 м',
      qScore: 85.5,
      flavorNotes: ['Молочный шоколад', 'Карамель', 'Красное яблоко', 'Фундук'],
      recommendedBrew: ['Эспрессо', 'Гейзер (Moka)', 'Автомат', 'Чашка'],
      acidity: 3,
      sweetness: 5,
      bitterness: 2,
      body: 4,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-3',
    slug: 'brazil-cerrado-dulce',
    title: 'Brazil Cerrado Dulce Espresso',
    category: 'espresso-blends',
    categoryName: 'Эспрессо-бленды',
    brandId: 'br-tav-signature',
    brandName: 'ТАВ Signature Roasts',
    countryId: 'cnt-br',
    countryName: 'Бразилия',
    countryCode: 'BR',
    price: 760,
    inStock: true,
    stockCount: 18,
    description: 'Насыщенная средняя/тёмная обжарка для любителей классического густого эспрессо без выраженной кислинки. Плотная бархатная пенка крема, долгое ореховое послевкусие и ноты бельгийского темного какао.',
    shortDescription: 'Тёмная обжарка с нотами тёмного шоколада, жареного фундука и патоки.',
    images: [
      'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: false,
    publishedAt: '2026-01-10T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Желтый Бурбон, Мундо Ново)',
      roastLevel: 'dark',
      processing: 'Натуральная (Natural)',
      altitude: '1 100 – 1 250 м',
      qScore: 84.0,
      flavorNotes: ['Тёмный шоколад', 'Жареный фундук', 'Патока', 'Тростниковый сахар'],
      recommendedBrew: ['Эспрессо', 'Капучино / Латте', 'Гейзер', 'Турка'],
      acidity: 1,
      sweetness: 4,
      bitterness: 4,
      body: 5,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-4',
    slug: 'guatemala-antigua-estate',
    title: 'Guatemala Antigua Pastoral',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-gt',
    countryName: 'Гватемала',
    countryCode: 'GT',
    price: 850,
    inStock: true,
    stockCount: 10,
    description: 'Вулканические почвы региона Антигуа дарят этому лоту неповторимый пряный характер. В букете переплетаются ноты сушеного абрикоса, цедры красного апельсина и какао-бобов с дымным нюансом.',
    shortDescription: 'Средняя обжарка с нотами кураги, темного шоколада и апельсиновой цедры.',
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: false,
    isFeatured: false,
    publishedAt: '2026-02-18T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Бурбон, Типика)',
      roastLevel: 'medium',
      processing: 'Мытая (Washed)',
      altitude: '1 500 – 1 700 м',
      qScore: 86.0,
      flavorNotes: ['Курага', 'Тёмный шоколад', 'Цедра апельсина', 'Мускатный орех'],
      recommendedBrew: ['V60', 'Фильтр', 'Аэропресс', 'Гейзер'],
      acidity: 3,
      sweetness: 4,
      bitterness: 2,
      body: 3,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-5',
    slug: 'kenya-aa-nyeri-hill',
    title: 'Kenya AA Nyeri Hill Selection',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-ke',
    countryName: 'Кения',
    countryCode: 'KE',
    price: 940,
    inStock: true,
    stockCount: 16,
    description: 'Ярчайший эталон африканского спешелти кофе. Спелая черная смородина, сочный грейпфрут и тягучая сладость тростникового сахара. Сложная многогранная кислотность и кристально чистый финиш.',
    shortDescription: 'Светлая обжарка с нотами черной смородины, грейпфрута и черного чая.',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-02-20T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (SL28, SL34)',
      roastLevel: 'light',
      processing: 'Мытая (Washed)',
      altitude: '1 800 – 2 100 м',
      qScore: 88.5,
      flavorNotes: ['Чёрная смородина', 'Грейпфрут', 'Чёрный чай', 'Тростниковый сахар'],
      recommendedBrew: ['V60 Воронка', 'Кемекс', 'Фильтр', 'Аэропресс'],
      acidity: 5,
      sweetness: 4,
      bitterness: 1,
      body: 3,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-6',
    slug: 'tav-signature-espresso-blend',
    title: 'ТАВ Signature Espresso Blend',
    category: 'espresso-blends',
    categoryName: 'Эспрессо-бленды',
    brandId: 'br-tav-signature',
    brandName: 'ТАВ Signature Roasts',
    countryId: 'cnt-br',
    countryName: 'Бразилия & Колумбия',
    countryCode: 'BR',
    price: 790,
    inStock: true,
    stockCount: 30,
    description: 'Фирменный купаж обжарщиков ТАВ: 70% натуральной Бразилии Серрадо и 30% мытой Колумбии Уила. Идеальный баланс мягкой цитрусовой сладости, плотного сливочного тела и густой карамельной пенки.',
    shortDescription: 'Средняя обжарка с нотами пралине, темного шоколада и сливочной ириски.',
    images: [
      'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-01-05T10:00:00Z',
    coffeeSpecs: {
      variety: 'Купаж 100% Арабики',
      roastLevel: 'medium',
      processing: 'Natural / Washed Blend',
      altitude: '1 200 – 1 750 м',
      qScore: 85.0,
      flavorNotes: ['Пралине', 'Тёмный шоколад', 'Сливочная ириска', 'Фундук'],
      recommendedBrew: ['Эспрессо', 'Капучино / Латте', 'Гейзер', 'Автомат'],
      acidity: 2,
      sweetness: 5,
      bitterness: 2,
      body: 5,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-7',
    slug: 'costa-rica-tarrazu-anaerobic',
    title: 'Costa Rica Tarrazú Anaerobic Microlot',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-cr',
    countryName: 'Коста-Рика',
    countryCode: 'CR',
    price: 1150,
    inStock: true,
    stockCount: 8,
    description: 'Эксклюзивная анаэробная ферментация в герметичных емкостях в течение 72 часов. Невероятный взрыв клубничного джема, выдержанного рома, спелого манго и ванили. Лимитированная партия.',
    shortDescription: 'Светлая обжарка с нотами клубничного джема, пряного рома и манго.',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-02-22T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Катуаи)',
      roastLevel: 'light',
      processing: 'Анаэробная (Anaerobic 72h)',
      altitude: '1 750 – 1 900 м',
      qScore: 89.0,
      flavorNotes: ['Клубничный джем', 'Пряный ром', 'Манго', 'Бурбонская ваниль'],
      recommendedBrew: ['V60 Воронка', 'Кемекс', 'Аэропресс'],
      acidity: 4,
      sweetness: 5,
      bitterness: 1,
      body: 3,
      weight: 250,
    },
  },
  {
    id: 'prod-coffee-8',
    slug: 'rwanda-inzovu-bourbon',
    title: 'Rwanda Inzovu Red Bourbon',
    category: 'single-origin',
    categoryName: 'Моносорта & Микролоты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-rw',
    countryName: 'Руанда',
    countryCode: 'RW',
    price: 880,
    inStock: true,
    stockCount: 12,
    description: 'Высокогорный мытый Красный Бурбон с берегов озера Киву. Шелковистое тело, ноты спелой красной вишни, цветков ройбуша и теплого липового меда. Долгое сочное послевкусие.',
    shortDescription: 'Светло-средняя обжарка с нотами красной вишни, ройбуша и мёда.',
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: false,
    isFeatured: false,
    publishedAt: '2026-01-15T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика (Red Bourbon)',
      roastLevel: 'light',
      processing: 'Мытая (Washed)',
      altitude: '1 700 – 2 000 м',
      qScore: 86.5,
      flavorNotes: ['Красная вишня', 'Ройбуш', 'Липовый мёд', 'Красное яблоко'],
      recommendedBrew: ['V60', 'Фильтр', 'Аэропресс'],
      acidity: 4,
      sweetness: 4,
      bitterness: 1,
      body: 3,
      weight: 250,
    },
  },

  // ==========================================
  // ДРИП-ПАКЕТЫ (Drip Coffee)
  // ==========================================
  {
    id: 'prod-drip-1',
    slug: 'tav-drip-box-mix-10',
    title: 'ТАВ Drip Box — Mix 10 шт (Ассорти моносортов)',
    category: 'drip-coffee',
    categoryName: 'Дрип-пакеты',
    brandId: 'br-tav-drip',
    brandName: 'ТАВ Drip Coffee Lab',
    countryId: 'cnt-et',
    countryName: 'Микс стран',
    price: 950,
    inStock: true,
    stockCount: 25,
    description: 'Набор из 10 дрип-пакетов свежего спешелти кофе в индивидуальных саше с азотом. Внутри: 2× Эфиопия Иргачефф, 2× Колумбия Уила, 2× Кения Ньери, 2× Коста-Рика Анаэробика, 2× Гватемала Антигуа. Идеально для офиса и путешествий.',
    shortDescription: '10 дрип-пакетов лучших моносортов ТАВ в подарочном боксе.',
    images: [
      'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-02-10T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Спешелти Арабика (Ассорти лотов)',
      roastLevel: 'light',
      flavorNotes: ['Ягоды', 'Цветы', 'Цитрус', 'Шоколад', 'Карамель'],
      count: 10,
      weight: 115,
    },
  },
  {
    id: 'prod-drip-2',
    slug: 'tav-drip-box-ethiopia-10',
    title: 'ТАВ Drip Box — Ethiopia Yirgacheffe (10 шт)',
    category: 'drip-coffee',
    categoryName: 'Дрип-пакеты',
    brandId: 'br-tav-drip',
    brandName: 'ТАВ Drip Coffee Lab',
    countryId: 'cnt-et',
    countryName: 'Эфиопия',
    countryCode: 'ET',
    price: 920,
    inStock: true,
    stockCount: 19,
    description: '10 дрип-пакетов высокогорной мытой Эфиопии. Нежнейшие ноты жасмина, бергамота и персика за пару минут в любой чашке. Требуется только горячая вода.',
    shortDescription: '10 дрип-пакетов светлой обжарки: жасмин, бергамот и персик.',
    images: [
      'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: false,
    publishedAt: '2026-01-28T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика Эфиопия Иргачефф',
      roastLevel: 'light',
      processing: 'Мытая (Washed)',
      flavorNotes: ['Жасмин', 'Бергамот', 'Персик', 'Лайм'],
      count: 10,
      weight: 115,
    },
  },
  {
    id: 'prod-drip-3',
    slug: 'tav-drip-box-colombia-brazil-10',
    title: 'ТАВ Drip Box — Colombia & Brazil Balance (10 шт)',
    category: 'drip-coffee',
    categoryName: 'Дрип-пакеты',
    brandId: 'br-tav-drip',
    brandName: 'ТАВ Drip Coffee Lab',
    countryId: 'cnt-co',
    countryName: 'Колумбия & Бразилия',
    price: 890,
    inStock: true,
    stockCount: 20,
    description: '10 дрип-пакетов со сбалансированным шоколадно-ореховым и карамельным профилем. Средняя обжарка, умеренная приятная сладость, комфортное тело.',
    shortDescription: '10 дрип-пакетов средней обжарки: молочный шоколад, фундук, карамель.',
    images: [
      'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: false,
    isFeatured: false,
    publishedAt: '2026-01-18T10:00:00Z',
    coffeeSpecs: {
      variety: '100% Арабика Колумбия + Бразилия',
      roastLevel: 'medium',
      flavorNotes: ['Молочный шоколад', 'Фундук', 'Карамель', 'Красное яблоко'],
      count: 10,
      weight: 115,
    },
  },

  // ==========================================
  // ДЕГУСТАЦИОННЫЕ СЕТЫ (Sets)
  // ==========================================
  {
    id: 'prod-set-1',
    slug: 'tav-discovery-tasting-box',
    title: 'ТАВ Discovery Tasting Box (4 × 100г)',
    category: 'sets',
    categoryName: 'Дегустационные сеты',
    brandId: 'br-tav-origin',
    brandName: 'ТАВ Single Origin',
    countryId: 'cnt-et',
    countryName: 'Микс стран',
    price: 1750,
    inStock: true,
    stockCount: 15,
    description: 'Премиальный дегустационный бокс с четырьмя моносортами свежей обжарки по 100 грамм: Эфиопия Иргачефф, Кения Ньери, Коста-Рика Анаэробика и Колумбия Уила. В комплекте карточки дескрипторов и колесо вкусов SCA.',
    shortDescription: 'Подарочный бокс с 4 моносортами по 100г для исследования вкусов.',
    images: [
      'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: true,
    isFeatured: true,
    publishedAt: '2026-02-12T10:00:00Z',
    coffeeSpecs: {
      variety: '4 микролота 100% Арабики',
      roastLevel: 'light',
      flavorNotes: ['Бергамот', 'Черная смородина', 'Клубника', 'Шоколад'],
      weight: 400,
    },
  },

  // ==========================================
  // АКСЕССУАРЫ И ЗАВАРИВАНИЕ (Accessories)
  // ==========================================
  {
    id: 'prod-acc-1',
    slug: 'hario-v60-ceramic-02-black',
    title: 'Воронка Hario V60 02 Ceramic Matte Black',
    category: 'accessories',
    categoryName: 'Аксессуары и заваривание',
    brandId: 'br-hario',
    brandName: 'Hario',
    countryId: 'cnt-jp',
    countryName: 'Япония',
    countryCode: 'JP',
    price: 2890,
    inStock: true,
    stockCount: 9,
    description: 'Культовая японская керамическая воронка для приготовления фильтр-кофе методом Pour Over на 1-4 чашки. Ребристые спиральные стенки и угол 60 градусов обеспечивают идеальную экстракцию.',
    shortDescription: 'Японская керамическая воронка для чистого и яркого фильтр-кофе.',
    images: [
      'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: true,
    isFeatured: false,
    publishedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-acc-2',
    slug: 'timemore-chestnut-c3-pro',
    title: 'Кофемолка ручная Timemore Chestnut C3 PRO',
    category: 'accessories',
    categoryName: 'Аксессуары и заваривание',
    brandId: 'br-timemore',
    brandName: 'Timemore',
    countryId: 'cnt-jp',
    countryName: 'Япония',
    price: 5400,
    inStock: true,
    stockCount: 6,
    description: 'Флагманская ручная кофемолка с запатентованными коническими стальными жерновами Spike-to-Cut (S2C 660). Сверхточная плавная регулировка помола: от тонкого эспрессо и турки до крупного фильтра и френч-пресса.',
    shortDescription: 'Стальные жернова S2C, алюминиевый корпус, складная рукоятка.',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: true,
    isPopular: true,
    isFeatured: false,
    publishedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod-acc-3',
    slug: 'hario-v60-range-server-600',
    title: 'Сервер для кофе Hario V60 600 мл',
    category: 'accessories',
    categoryName: 'Аксессуары и заваривание',
    brandId: 'br-hario',
    brandName: 'Hario',
    countryId: 'cnt-jp',
    countryName: 'Япония',
    countryCode: 'JP',
    price: 1650,
    inStock: true,
    stockCount: 14,
    description: 'Кофейный сервер из жаропрочного японского стекла с мерной шкалой и стеклянной крышкой с силиконовым уплотнителем. Совместим со всеми воронками Hario V60 размера 01 и 02.',
    shortDescription: 'Кувшин из японского термостекла 600мл для подачи свежего фильтр-кофе.',
    images: [
      'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
    ],
    isNew: false,
    isPopular: false,
    isFeatured: false,
    publishedAt: '2026-01-25T10:00:00Z',
  },
];
